export const palettes = [
  {
    id: "a",
    label: "default",
    palette: {
      themePrimary: "#0481e0",
      themeLighterAlt: "#f4f9fe",
      themeLighter: "#d3e9fa",
      themeLight: "#aed7f6",
      themeTertiary: "#61b0ed",
      themeSecondary: "#1f8fe4",
      themeDarkAlt: "#0474ca",
      themeDark: "#0362ab",
      themeDarker: "#03487e",
    },
  },
  {
    id: "b",
    label: "blueLight",
    palette: {
      themePrimary: "#2694bf",
      themeLighterAlt: "#f4f9fe",
      themeLighter: "#d3e9fa",
      themeLight: "#aed7f6",
      themeTertiary: "#518ebd",
      themeSecondary: "#2274A5",
      themeDarkAlt: "#007399",
      themeDark: "#006080",
      themeDarker: "#3f7cab",
    },
  },
  {
    id: "n",
    label: "viridian-green",
    palette: {
      themePrimary: "#239E9A",
      themeLighterAlt: "#f2fcfb",
      themeLighter: "#c3ebe9",
      themeLight: "#94d9d5",
      themeTertiary: "#3eaeaa",
      themeSecondary: "#1f8c89",
      themeDarkAlt: "#20847f",
      themeDark: "#1a6d6a",
      themeDarker: "#124b48",
    },
  },
  {
    id: "c",
    label: "sky",
    palette: {
      themePrimary: "#303f9f",
      themeLighterAlt: "#f3f4fc",
      themeLighter: "#c5c8e9",
      themeLight: "#9599d4",
      themeTertiary: "#4d52a8",
      themeSecondary: "#2c3182",
      themeDarkAlt: "#19226d",
      themeDark: "#151b5a",
      themeDarker: "#0f1240",
    },
  },
  {
    id: "d",
    label: "red",
    palette: {
      themePrimary: "#F55C47",
      themeLighterAlt: "#fef4f4",
      themeLighter: "#f7c5be",
      themeLight: "#f19a8b",
      themeTertiary: "#e04d2d",
      themeSecondary: "#e47a5c",
      themeDarkAlt: "#d34f3b",
      themeDark: "#ab462f",
      themeDarker: "#7e3a25",
    },
  },
  {
    id: "m",
    label: "ia-1",
    palette: {
      themePrimary: "#8B008B",
      themeLighterAlt: "#f9f4fa",
      themeLighter: "#e1c2e1",
      themeLight: "#c08ac0",
      themeTertiary: "#853085",
      themeSecondary: "#a64da6",
      themeDarkAlt: "#6d006d",
      themeDark: "#5c005c",
      themeDarker: "#3f003f",
    },
  },
  {
    id: "l",
    label: "ia-2",
    palette: {
      themePrimary: "#2E8B57",
      themeLighterAlt: "#f4fdf7",
      themeLighter: "#c9e9d4",
      themeLight: "#9dd5b0",
      themeTertiary: "#4daa6b",
      themeSecondary: "#2e8b57",
      themeDarkAlt: "#297d4c",
      themeDark: "#246b41",
      themeDarker: "#1a4c2f",
    },
  },
  {
    id: "e",
    label: "ia-3",
    palette: {
      themePrimary: "#FF69B4",
      themeLighterAlt: "#fef4f9",
      themeLighter: "#f7c2d6",
      themeLight: "#f19ab1",
      themeTertiary: "#e03d6a",
      themeSecondary: "#e47a8c",
      themeDarkAlt: "#d34e5c",
      themeDark: "#ab4550",
      themeDarker: "#7e363b",
    },
  },
  {
    id: "f",
    label: "yellow",
    palette: {
      themePrimary: "#f7b731",
      themeLighterAlt: "#fef9f2",
      themeLighter: "#fde5c1",
      themeLight: "#facd7e",
      themeTertiary: "#f5a500",
      themeSecondary: "#e68e00",
      themeDarkAlt: "#cc7d00",
      themeDark: "#a86c00",
      themeDarker: "#805400",
    },
  },
  {
    id: "g",
    label: "summer",
    palette: {
      themePrimary: "#f5a623",
      themeLighterAlt: "#fef8f2",
      themeLighter: "#fde0c1",
      themeLight: "#fac17e",
      themeTertiary: "#f58c00",
      themeSecondary: "#e06d00",
      themeDarkAlt: "#d15500",
      themeDark: "#b84b00",
      themeDarker: "#8e3900",
    },
  },
  {
    id: "h",
    label: "ia-4",
    palette: {
      themePrimary: "#c7a3d9",
      themeLighterAlt: "#fcf9fe",
      themeLighter: "#e4d1f0",
      themeLight: "#cda1d6",
      themeTertiary: "#a75fa8",
      themeSecondary: "#8b3e8f",
      themeDarkAlt: "#7c347e",
      themeDark: "#632b67",
      themeDarker: "#4a1f4b",
    },
  },
  {
    id: "i",
    label: "ia-5",
    palette: {
      themePrimary: "#e63061",
      themeLighterAlt: "#c92a55",
      themeLighter: "#bd3559",
      themeLight: "#bf506e",
      themeTertiary: "#db4670",
      themeSecondary: "#c23a5f",
      themeDarkAlt: "#a10b4e",
      themeDark: "#ad2147",
      themeDarker: "#9c3261",
    },
  },
]
